spring:
  datasource:
    url: jdbc:mysql://localhost:8889/transfer?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
  liquibase:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

# set accounts to transfer money from formatted as {"accountId": "sum",...}
accountsFrom:
  '{"1000000001": "5000", "1000000002": "200", "1000000003": "1000"}'

# set accounts to receive money formatted as enumeration
accountsTo:
#  1000000004,1000000005,1000000006
  '{"1000000004", "1000000005", "1000000006"}'
